const ERROR_SERVER = 500;
const ERROR_NOT_FOUND = 404;
const ERROR_CODE = 400;
const ERROR_DUBLICATE = 409;
const ERROR_AUTHORIZED = 401;
const ERROR_OWNER = 403;

module.exports = {
  ERROR_SERVER,
  ERROR_NOT_FOUND,
  ERROR_CODE,
  ERROR_DUBLICATE,
  ERROR_AUTHORIZED,
  ERROR_OWNER,
};
